/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package full.house;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;


/**
 *
 * @author Tim
 */
public class AddSpeler extends javax.swing.JFrame {

    SpelerView parent;
    String naam;
    String voorletters;
    String postcode;
    String woonplaats;
    String straatnaam;
    String huisNr;
    String telefoonNr;
    String email;
    /**
     * Creates new form AddUserFrame
     */
    public AddSpeler(SpelerView parent) {
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addUserLbl = new javax.swing.JLabel();
        naamLbl = new javax.swing.JLabel();
        voorlettersLbl = new javax.swing.JLabel();
        straatHuisNrLbl = new javax.swing.JLabel();
        woonplaatsLbl = new javax.swing.JLabel();
        postcodeLbl = new javax.swing.JLabel();
        telefoonNrLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        naamField = new javax.swing.JTextField();
        voorlettersField = new javax.swing.JTextField();
        straatnaamField = new javax.swing.JTextField();
        huisNrField = new javax.swing.JTextField();
        woonplaatsField = new javax.swing.JTextField();
        postcodeField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        docentCB = new javax.swing.JCheckBox();
        warningLbl = new javax.swing.JLabel();
        telefoonNrField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nieuwe speler");

        addUserLbl.setText("Voeg speler toe");

        naamLbl.setText("naam:");

        voorlettersLbl.setText("voorletters:");

        straatHuisNrLbl.setText("straatnaam & huisnr:");

        woonplaatsLbl.setText("woonplaats:");

        postcodeLbl.setText("postcode:");

        telefoonNrLbl.setText("telefoon nr:");

        emailLbl.setText("E-mail adres:");

        addBtn.setText("Add");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });

        docentCB.setText("Docent");

        warningLbl.setForeground(new java.awt.Color(240, 240, 240));
        warningLbl.setText("jLabel1");

        telefoonNrField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefoonNrFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addUserLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(straatHuisNrLbl)
                                    .addComponent(woonplaatsLbl)
                                    .addComponent(postcodeLbl)
                                    .addComponent(voorlettersLbl)
                                    .addComponent(telefoonNrLbl)
                                    .addComponent(emailLbl)
                                    .addComponent(naamLbl))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(docentCB)
                                    .addComponent(naamField)
                                    .addComponent(voorlettersField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(straatnaamField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(huisNrField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(postcodeField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(woonplaatsField)
                                    .addComponent(emailField)
                                    .addComponent(telefoonNrField))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(warningLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addUserLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naamLbl)
                    .addComponent(naamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voorlettersLbl)
                    .addComponent(voorlettersField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(straatHuisNrLbl)
                    .addComponent(huisNrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(straatnaamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(woonplaatsLbl)
                    .addComponent(woonplaatsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postcodeLbl)
                    .addComponent(postcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoonNrLbl)
                    .addComponent(telefoonNrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(docentCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Voegt een speler toe.
     * Laat een label zien als er een ongeldige postcode word ingevoerd.
     * @param evt 
     */
    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        if (getValues()) {
            if (FullHouse.checkPostcode(postcode)) {
                if (addSpeler()) {
                    this.setVisible(false);
                    this.dispose();
                }
            }
            else {
                warningLbl.setText("Ongeldige postcode! Formaat postcode: 1234AB.");
                warningLbl.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_addBtnMouseClicked

    /**
     * Sluit scherm af.
     * @param evt 
     */
    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelBtnMouseClicked

    /**
     * Controleert of er een geldig telefoonnummer word opgegeven.
     * @param evt 
     */
    private void telefoonNrFieldKeyTyped (java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefoonNrFieldKeyTyped
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_telefoonNrFieldKeyTyped

    /**
     * Voegt een speler toe aan de database.
     * Returns false als de speler niet is toegevoegd.
     * @return 
     */
    private boolean addSpeler () {
        String query = "INSERT INTO Speler(naam, voorletters, postcode, woonplaats, straatnaam, huisNr, telefoonNr, email, rating, gewonnenGeld, isDocent)"
                + "VALUES(?,?,?,?,?,?,?,?,?,?,?)";
            try {
            Connection conn = SimpleDataSource.getConnection();
            PreparedStatement stat = conn.prepareStatement(query);
            
            int rating = 100;
            int gewonnenGeld = 0;
            boolean isDocent = docentCB.isSelected();
            
            stat.setString(1, naam);
            stat.setString(2, voorletters);
            stat.setString(3, postcode);
            stat.setString(4, woonplaats);
            stat.setString(5, straatnaam);
            stat.setString(6, huisNr);
            stat.setString(7, telefoonNr);
            stat.setString(8, email);
            stat.setInt(9, rating);
            stat.setInt(10, gewonnenGeld);
            stat.setBoolean(11, isDocent);
            
            stat.executeUpdate();
            stat.close();
        }
        catch (Exception e) {
            FullHouse.showDBError(e);
            return false;
        }
        parent.getSpelers();
        return true;
    }
    
    /**
     * Haalt gegevens op uit de invoer velden.
     * Controleert of de invoer correct is.
     * @return Returns true wanneer alles goed is ingevult.
     */
    private boolean getValues () {
        naam = naamField.getText();
        voorletters = voorlettersField.getText();
        postcode = postcodeField.getText();
        woonplaats = woonplaatsField.getText();
        straatnaam = straatnaamField.getText();
        huisNr = huisNrField.getText();
        telefoonNr = telefoonNrField.getText();
        email = emailField.getText();
        if (naam.length() < 2) {
            warningLbl.setText("Naam moet minimaal twee karakters bevatten");
            warningLbl.setForeground(Color.red);
            return false;
        }
        else if (voorletters.length() < 1) {
            warningLbl.setText("Vul minimaal één voorletter in");
            warningLbl.setForeground(Color.red);
            return false;
        }
        else if (straatnaam.length() < 2) {
            warningLbl.setText("Vul een straatnaam in");
            warningLbl.setForeground(Color.red);
            return false;
        }
        else if (huisNr.length() < 1) {
            warningLbl.setText("Vul een huisnummer in");
            warningLbl.setForeground(Color.red);
            return false;
        }
        else if (woonplaats.length() < 2) {
            warningLbl.setText("Vul een woonplaats in");
            warningLbl.setForeground(Color.red);
            return false;
        }
        else if (telefoonNr.length() != 10) {
            warningLbl.setText("Telefoon nummer moet tien tekens lang zijn");
            warningLbl.setForeground(Color.red);
            return false;
        }
        else if (email.length() < 5 || !email.contains("@") || !email.contains(".")) {
            warningLbl.setText("Ongeldig email adres");
            warningLbl.setForeground(Color.red);
            return false;
        }
        else {
            return true;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel addUserLbl;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JCheckBox docentCB;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField huisNrField;
    private javax.swing.JTextField naamField;
    private javax.swing.JLabel naamLbl;
    private javax.swing.JTextField postcodeField;
    private javax.swing.JLabel postcodeLbl;
    private javax.swing.JLabel straatHuisNrLbl;
    private javax.swing.JTextField straatnaamField;
    private javax.swing.JFormattedTextField telefoonNrField;
    private javax.swing.JLabel telefoonNrLbl;
    private javax.swing.JTextField voorlettersField;
    private javax.swing.JLabel voorlettersLbl;
    private javax.swing.JLabel warningLbl;
    private javax.swing.JTextField woonplaatsField;
    private javax.swing.JLabel woonplaatsLbl;
    // End of variables declaration//GEN-END:variables
}
