/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package full.house;

import java.awt.CardLayout;

/**
 *
 * @author Tim
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewSpelersBtn = new javax.swing.JButton();
        viewToernooienBtn = new javax.swing.JButton();
        ViewMCBtn = new javax.swing.JButton();
        viewLocatiesBtn = new javax.swing.JButton();
        cards = new javax.swing.JPanel();
        spelerView = new full.house.SpelerView();
        toernooiView = new full.house.ToernooiView();
        locatieView = new full.house.LocatieView();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Full House registratie-programma");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        viewSpelersBtn.setText("Spelers");
        viewSpelersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSpelersBtnMouseClicked(evt);
            }
        });

        viewToernooienBtn.setText("Toernooien");
        viewToernooienBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewToernooienBtnMouseClicked(evt);
            }
        });

        ViewMCBtn.setText("Master Classes");

        viewLocatiesBtn.setText("Locaties");
        viewLocatiesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewLocatiesBtnMouseClicked(evt);
            }
        });

        cards.setLayout(new java.awt.CardLayout());
        cards.add(spelerView, "spelerView");
        cards.add(toernooiView, "toernooiView");
        cards.add(locatieView, "locatieView");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewSpelersBtn)
                .addGap(18, 18, 18)
                .addComponent(viewToernooienBtn)
                .addGap(18, 18, 18)
                .addComponent(ViewMCBtn)
                .addGap(18, 18, 18)
                .addComponent(viewLocatiesBtn)
                .addGap(0, 187, Short.MAX_VALUE))
            .addComponent(jSeparator2)
            .addComponent(cards, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ViewMCBtn, viewLocatiesBtn, viewSpelersBtn, viewToernooienBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewSpelersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewToernooienBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewMCBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewLocatiesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cards, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewToernooienBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewToernooienBtnMouseClicked
        CardLayout cl = (CardLayout) cards.getLayout();
        cl.show(cards, "toernooiView");
    }//GEN-LAST:event_viewToernooienBtnMouseClicked

    private void viewSpelersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSpelersBtnMouseClicked
        CardLayout cl = (CardLayout) cards.getLayout();
        cl.show(cards, "spelerView");
    }//GEN-LAST:event_viewSpelersBtnMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            SimpleDataSource.closeConnection();
            System.out.println("Connection closed.");
        }
        catch (Exception e) {
            System.out.println(e);
            System.out.println("Could not close connection!");
        }
    }//GEN-LAST:event_formWindowClosing

    private void viewLocatiesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewLocatiesBtnMouseClicked
        CardLayout cl = (CardLayout) cards.getLayout();
        cl.show(cards, "locatieView");
    }//GEN-LAST:event_viewLocatiesBtnMouseClicked
    
    
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewMCBtn;
    private javax.swing.JPanel cards;
    private javax.swing.JSeparator jSeparator2;
    private full.house.LocatieView locatieView;
    private full.house.SpelerView spelerView;
    private full.house.ToernooiView toernooiView;
    private javax.swing.JButton viewLocatiesBtn;
    private javax.swing.JButton viewSpelersBtn;
    private javax.swing.JButton viewToernooienBtn;
    // End of variables declaration//GEN-END:variables
}
